// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"Yanatsuki_BeforeCommon_MZ_edited","status":true,"description":"ver1.01/スキルやアイテムの発動前に、スキルやアイテムに設定されたコモンイベントを発生させます。","parameters":{"IndexVariableID":"51","TargetIndexVariableID":"52","nullNumberCommonReserve":"true"}},
{"name":"TorigoyaMZ_SameEquipType","status":true,"description":"同じ名前の装備タイプなら同じものを装備できるようにするプラグイン (v.1.0.0)","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"EventReSpawn","status":true,"description":"Event Dynamic Generation","parameters":{"keepSelfSwitch":"false","variableSpawnEventId":"0"}},
{"name":"MessageWindowPopup","status":true,"description":"Balloon Window Plugin","parameters":{"FontSize":"28","Padding":"18","AutoPopup":"false","FaceScale":"75","WindowLinkage":"true","BetweenLines":"4","FontSizeRange":"12","FontUpperLimit":"96","FontLowerLimit":"24","InnerScreen":"false","ShakeSpeed":"5","ShakeDuration":"60","NoUseTail":"true","MinWidthVariableId":"0","MinHeightVariableId":"0","lowerLimitX":"0","upperLimitX":"0","lowerLimitY":"0","upperLimitY":"0","tailImage":"","tailImageAdjustY":"0"}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"Chimaki_MsgTool","status":true,"description":"one times center msg","parameters":{}},
{"name":"FilterControllerMZ","status":true,"description":"FilterControllerMZ","parameters":{"decimalVariable":"true","displacementImage":"DisplacementMap","global-enable Settings":"","enabledAll-ShowInOptionMenu":"false","enabledAll-Text":"Filter Effects Enabled","enabledAll-DefaultValue":"true"}},
{"name":"GALV_CamControlMZ","status":true,"description":"(v.1.8) Allows greater control over where the game camera is focused. View documentation for plugin commands.","parameters":{"useZoom":"true","bZoom":"1"}},
{"name":"WD_ConditionalChoice_v2_1_1","status":true,"description":"Allow to input a check in the \"Show Choice\" that disables or hide the choice.","parameters":{"disabledSE":"","hiddenDefault":"hidden1","alternativeText":"[]","errorHandling":"error1"}}
];
